name: User story
description: A user-facing slice of work
type: story
labels:
  - "needs-triage"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
